export const projectData = [
    {
        icon: "/portfolio/zombies_web.jpeg",
        title: "Zombies-R-Us App Landing Page",
        link: "https://zombies.bivensblueprint.com",
        description: "A simple landing page website example promoting an app download. This site was originally built following an online course using pure HTML & CSS but has been updated using latest NextJS, Tailwind & HeroUI technologies and design principles.",
        height: "260",
        width: "260",
    },
    {
        icon: "/portfolio/dreamers_web.jpeg",
        title: "Dreamers Dance Studio",
        link: "https://dreamers.bivensblueprint.com",
        description: "This project showcases a simple business website and standard features. It is modeled after a Dance and Model studio. All images are template photos found online and belong to their respective owners. The information is also sampled meant as logical placeholders.",
        height: "260",
        width: "260",
    },
    {
        icon: "/portfolio/stormtrooper_web.jpeg",
        title: "Stormtrooper University",
        link: "https://stormtrooper.bivensblueprint.com",
        description: "This is a single-page concept website. It was developed to display animations throughout the site with plentiful graphics.",
        height: "260",
        width: "260",
    },
    {
        icon: "/portfolio/sptemplate01_web.jpeg",
        title: "Conversion Site Template 01",
        link: "https://template01.bivensblueprint.com",
        description: "A conversion website showcasing all necessary components of a website. Its singular, straightforward layout is designed to preserve attention on your message without distracting to visuals or unnecessary components. Perfect for businesses who want to focus on their service.",
        package: 'Available Templates',
        height: "260",
        width: "260",
    },
    {
        icon: "/portfolio/sptemplate02_web.jpeg",
        title: "Conversion Site Template 02",
        link: "https://template02.bivensblueprint.com",
        description: "A conversion website modeled after a construction business. This site emphasizes a Service Provider. It garners trust and clarity of what you do with minimal guesswork. The clear Call to Action ensures clients know exactly how to contact you. Great for any service industry where you need you need to introduce your business, gain trust, and direct clients to next steps.",
        height: "260",
        width: "260",
    },
    {
        icon: "/portfolio/johnnys_web.jpeg",
        title: "Johnny's E-Commerce",
        link: "https://johnnys2-0.bivensblueprint.com",
        description: "An e-commerce website that uses Stripe and Sanity as the payment processor and backend. The payment functions are not functional but showcases a layout and proof of concept.",
        package: 'Personal Projects',
        height: "260",
        width: "260",
    },
    {
        icon: "/portfolio/sptemplate03_web.jpeg",
        title: "Conversion Site Template 03",
        link: "https://template03.bivensblueprint.com",
        description: "A conversion website design to. This website is intentionally minimal as to ensure clients are not overloaded with content. It is great for providers who want to redirect clients to contacting them instead of getting lost in images and statistics.",
        package: "Available Templates",
        height: "260",
        width: "260",
    },
    {
        icon: "/portfolio/mptemplate_web.jpeg",
        title: "Growth Site Template 01",
        link: "https://emberandoak.vercel.app",
        description: "A growth website example. Themed after a fictional coffee shop, this site is designed to present a production-ready website for a local small business. Growth websites segment data across webpages to ensure customers are not overloaded with infinite scrolling",
        height: "260",
        width: "260",
    },
    {
        icon: "/portfolio/mptemplate02_web.jpeg",
        title: "Growth Site Template 02",
        link: "https://sugarrushcupcakes.vercel.app",
        description: "A growth website themed after a cupcake shop. It emphasizes mood and color schemes to pull customers in. Branding is important to remain memorable and communicate your message visually. It is designed to house product photos in an aesthetically pleasing manner.",
        height: "260",
        width: "260",
    },
    {
        icon: "/portfolio/mptemplate03_web.jpeg",
        title: "Growth Site Template 03",
        link: "https://powerwashtemplate.vercel.app",
        description: "A Growth website to showcase a service business. This site uses an unbranded and branded theme switch to give you the idea of what your website could look like. It is structured to provide all necessary information on the main page with supplemental information on their own pages. This ensures clients have direct access to information upfront without it being buried behind pages.",
        height: "260",
        width: "260",
    },
    
]