export const projectData = [
    {
        id: 6,
        icon: "https://www.blueprintwebdev.com/_next/image?url=%2Fimages%2FNewGradLogo.png&w=3840&q=75",
        title: "New Grad Recruitment",
        link: "https://newgrad.bivensblueprint.com",
        height: "260",
        width: "260",
        description: "This one is a passion project of mine. It showcases almost everything I know and more. It's built using Material UI. I am particularly proud of this one, as it is a relatively large project. You'll find databases, passwords and conditional functions throughout the site.",
    },
    {
        id: 9,
        icon: "https://www.blueprintwebdev.com/_next/image?url=%2Fimages%2FJohnnysLogo.png&w=3840&q=75",
        title: "Johnny's",
        link: "http://johnnys.bivensblueprint.com",
        height: "260",
        width: "260",
        description: "A web store with a material design. The database for the inventory has unfortunately gone defunct, so images will not load. It includes everything needed to start a web store including a shopping cart and inventory management.",
    },
    {
        id: 12,
        icon: "https://www.blueprintwebdev.com/_next/image?url=%2Fimages%2Frusselltransportlogo.png&w=3840&q=75",
        title: "Russell's Transport",
        link: "https://russellstransportllc.com",
        height: "260",
        width: "260",
        description: "This is an evolution of OB&T Dispatching. Built to represent the company's expanded vision and additional services. While it is still a landing page, it showcases additional functions to allow the company to grow and continue to establish their online presence.",
    },
    {
        id: 14,
        icon: "https://www.blueprintwebdev.com/_next/image?url=%2Fimages%2Fchapter_logo.jpg&w=3840&q=75",
        title: "Alpha Phi Alpha | Pi Iota Lambda",
        link: "https://piiotalambdaalphas.com",
        height: "260",
        width: "260",
        description: "A website for the Pi Iota Lambda chapter of Alpha Phi Alpha. This website uses the bleeding edge framework of Next 13. You'll notice it loads fast and utilizes many components to showcase the chapter and their programs. The Admin pages allows uploading images, adding messages and editing member info.",
    },
    {
        id: 15,
        icon: "https://www.blueprintwebdev.com/_next/image?url=%2Fimages%2Fdreamerslogo.png&w=3840&q=75",
        title: "Dreamers Dance Studio",
        link: "https://dreamers.bivensblueprint.com",
        height: "260",
        width: "260",
        description: "This project showcases a simple business website and standard features. It is modeled after a Dance and Model studio. All images are template photos found online and belong to their respective owners. The information is also sampled meant as logical placeholders.",
    },
    {
        id: 18,
        icon: "https://www.blueprintwebdev.com/_next/image?url=%2Fimages%2FacademyLogo.jpeg&w=3840&q=75",
        title: "Stormtrooper University",
        link: "https://stormtrooper.bivensblueprint.com",
        height: "260",
        width: "260",
        description: "This is a single-page website sample. It is to show a sample layout of a website that contains all of its information in a single page.",
    },
    {
        id: 19,
        icon: "https://www.blueprintwebdev.com/_next/image?url=%2Fimages%2Ftemplate01.png&w=3840&q=75",
        title: "Template - Your Awesome Business",
        link: "https://template01.bivensblueprint.com",
        height: "260",
        width: "260",
        description: "A Template Website for a service business. It is everything you need to get your business online.",
    },
    {
        id: 20,
        icon: "https://www.blueprintwebdev.com/_next/image?url=%2Fimages%2Fworksite.jpg&w=3840&q=75",
        title: "Template - Your Construction Business",
        link: "https://template02.bivensblueprint.com",
        height: "260",
        width: "260",
        description: "TAnother template website for a sample construction business. This project showcases a business that does not sell directly from the site, but advertises its services.",
    },
]